### ISSUE TITLE
Log in issue after sign up

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#12]
**Describe the bug**
I register (without getting to the third registration page and try to log back in and nothing happens.

http://testing.feefavor.com/register

**To Reproduce**
1. Go to '...'  http://testing.feefavor.com/register
2. Click on '....'  Already signed up? Log In!
then enter user name:  caddddyyyy@yahoo.com . with Pass: Jeffed197!
and I am not able to log in

**Expected behavior**
be able to log in

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by PendragonDevelopment** [comment]
Fixed.
