### ISSUE TITLE
searchers not showing up to select from at checkout

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#121]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![searchers not showing up](https://user-images.githubusercontent.com/43005119/59616165-becdba00-90d8-11e9-9545-d89a331c2f35.png)

**Comment by PendragonDevelopment** [comment]
@feefavor1 When did you set the requested by date for?

**Comment by feefavor1** [comment]
The day and time appear to be set for the time and day i enter the order.
If that does not get changed then I guess the order will not be
successful.  Should we make it mandatory for them to change the time and
day?

Also, when I changed the time and day for 24 hours, I am still not seeing
any searchers to choose from.

Cheers,

[image: user image]
Jeff Edrington
Founder
[image: facebook] <https://www.facebook.com/feefavor/>  [image: linkedin]
<https://www.linkedin.com/in/jeff-edrington-752ab7134/>  [image: twitter]
<https://twitter.com/FeeFavor>

**Comment by PendragonDevelopment** [comment]
We can set the default for 24 hours from the time it's entered, and I'll update the searcher table to show the available searchers if the turn time is the only difference?

**Comment by feefavor1** [comment]
that should work

Cheers,

[image: user image]
Jeff Edrington
Founder
[image: facebook] <https://www.facebook.com/feefavor/>  [image: linkedin]
<https://www.linkedin.com/in/jeff-edrington-752ab7134/>  [image: twitter]
<https://twitter.com/FeeFavor>
