### ISSUE TITLE
break in placing order

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#122]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![break on order screen](https://user-images.githubusercontent.com/43005119/59619852-4a971480-90e0-11e9-8512-5ff220eaa91e.png)

**Comment by PendragonDevelopment** [comment]
@feefavor1 Temporary fix - one of the entities didn't have a turn time set for Residential Full, have to find out how that happened

**Comment by feefavor1** [comment]
If you are talking about a searcher, there will be many that do not have
turn times loaded.

I also need to test showing e&o and non e&o to see what shows up and doesnt

Cheers,

[image: user image]
Jeff Edrington
Founder
[image: facebook] <https://www.facebook.com/feefavor/>  [image: linkedin]
<https://www.linkedin.com/in/jeff-edrington-752ab7134/>  [image: twitter]
<https://twitter.com/FeeFavor>
