### ISSUE TITLE
white screen after completing service section Go to payment led to a white screen

### ISSUE THREAD

**Issue by stevenvtff** [FeeFavor/feefavorV2#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by PendragonDevelopment** [comment]
Were any fields left empty?

**Comment by stevenvtff** [comment]
I did it both with everything filled and some left empty and got the same blank screen

**Comment by PendragonDevelopment** [comment]
Fixed.
