### ISSUE TITLE
copy cost included-two screen shots attached

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![copy cost inc](https://user-images.githubusercontent.com/43005119/59697525-ceb1d080-91a2-11e9-8049-9fba917f5137.png)
![default copies](https://user-images.githubusercontent.com/43005119/59697527-ceb1d080-91a2-11e9-954a-750338800f90.png)

**Comment by PendragonDevelopment** [comment]
Closing as duplicate.
