### ISSUE TITLE
banking info placement of buttons and verbiage on screen shot

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![banking info](https://user-images.githubusercontent.com/43005119/57249018-dada3800-7011-11e9-89fa-c15c2091e236.png)

**Comment by PendragonDevelopment** [comment]
Definitely possible, the business information required doesn't change regardless of which option they choose - does that matter?

**Comment by feefavor1** [comment]
I think it is just a placement issue.  I would rather them see that they
can "skip" this section (first) versus filling out a bit of the info and
then seeing they can skip that section.

Cheers,

[image: user image]
Jeff Edrington
Founder
[image: facebook] <https://www.facebook.com/feefavor/>  [image: linkedin]
<https://www.linkedin.com/in/jeff-edrington-752ab7134/>  [image: twitter]
<https://twitter.com/FeeFavor>
