### ISSUE TITLE
Remove "draft" selection on attached screen shot 

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![draft removal](https://user-images.githubusercontent.com/43005119/57249297-94d1a400-7012-11e9-86a3-7d47943b7d7f.png)
![draft removal](https://user-images.githubusercontent.com/43005119/57249324-a1ee9300-7012-11e9-902f-b526c1dea369.png)

**Comment by PendragonDevelopment** [comment]
Fixed.
