### ISSUE TITLE
counties and products fix on attached screen shot

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![products and counties](https://user-images.githubusercontent.com/43005119/57581920-b4daea80-748c-11e9-99b3-84c6b6213cc5.png)

**Comment by PendragonDevelopment** [comment]
This is how Qualia handles setting up county specific pricing. I can set it up for multiple county select, but it'll take 2-3 days.

**Comment by feefavor1** [comment]
the attached screen shot is how Qualia works

Cheers,

[image: user image]
Jeff Edrington
Founder
[image: facebook] <https://www.facebook.com/feefavor/>  [image: linkedin]
<https://www.linkedin.com/in/jeff-edrington-752ab7134/>  [image: twitter]
<https://twitter.com/FeeFavor>
