### ISSUE TITLE
beta testing and e&o on screen shot

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![e o numbers](https://user-images.githubusercontent.com/43005119/57801808-9beb6700-7722-11e9-8401-e30bd5d179a2.png)

**Comment by PendragonDevelopment** [comment]
The validation for this happens on the backend. I'll explain later.
