### ISSUE TITLE
cant see products on next screen per screen shot

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![product details](https://user-images.githubusercontent.com/43005119/58250220-e8403380-7d2e-11e9-8038-4205c25ec18d.png)

**Comment by PendragonDevelopment** [comment]
This is a duplicate of #44.
