### ISSUE TITLE
white page appears when don't type in numbers in address

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#7]
**Describe the bug**
If i don't enter "numbers" in the address line, I get sent to a white screen when I click on submit

i.e. one press place

Additionally, the city drop down box does not pre-populate cities, which means I could make a typo in a city name.

**To Reproduce**
1. Go to '...'  http://testing.feefavor.com/onboarding/profile

**Expected behavior**
to be able to complete registration

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by PendragonDevelopment** [comment]
@feefavor1 

1. City isn't a dropdown
2. Bug noted - if you reload the page, you should be able to continue
