### ISSUE TITLE
stuck on products screen on qa testing

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![products8](https://user-images.githubusercontent.com/43005119/58713268-36d57980-8390-11e9-9c5f-9a0869d59a62.png)

**Comment by PendragonDevelopment** [comment]
The removal is after you click through to the Dashboard and go to Manage Products - which is now fixed.
