### ISSUE TITLE
State not matching what I type

### ISSUE THREAD

**Issue by stevenvtff** [FeeFavor/feefavorV2#8]
**Describe the bug**
The letter I am typing for a state like Indiana --> "I" brings up Arizona before Indiana. Same if I were to type W for Washington. It brings up Delaware.
![States](https://user-images.githubusercontent.com/50242660/57236472-292c0e80-6ff3-11e9-99a8-7ebadffc9386.png)

**To Reproduce**

**Expected behavior**
The first letter I type matches the state name

**Screenshots**
![image](https://user-images.githubusercontent.com/50242660/57236523-4234bf80-6ff3-11e9-9149-6fcc627fd60c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by PendragonDevelopment** [comment]
This is the native behavior of the dropdown - if you were to continue with the next letter, it would filter based on that combo.

**Comment by stevenvtff** [comment]
I discussed with Jeff and he would like this to be resolved. 

If I type in "I" or "W" for Indiana or Washington, it will not bring up either state. However, if I type "H" Hawaii, the state Hawaii will pop up like Indiana (or another "I" State) and Washington should.

**Comment by stevenvtff** [comment]
I discussed with Jeff and he would like this to be resolved.

If I type in "I" or "W" for Indiana or Washington, it will not bring up either state. However, if I type "H" Hawaii, the state Hawaii will pop up like Indiana (or another "I" State) and Washington should.
