### ISSUE TITLE
sight order

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![order of sight](https://user-images.githubusercontent.com/43005119/59207969-21bdcf00-8b76-11e9-8ae6-7d7d44028f29.png)

**Comment by PendragonDevelopment** [comment]
Residential Search - n Year
