### ISSUE TITLE
pricing

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#99]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![prices showing up](https://user-images.githubusercontent.com/43005119/59208082-63e71080-8b76-11e9-8d63-67eea473cfc3.png)

**Comment by PendragonDevelopment** [comment]
Closing as duplicate.
Duplicate of #57
